apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/mnt/data" #